services:
  neo4j:
    image: neo4j:5
    environment:
      NEO4J_AUTH: "neo4j/pleaseChangeMe"
      NEO4J_server_memory_pagecache_size: 512M
      NEO4J_server_memory_heap_initial__size: 512M
      NEO4J_server_memory_heap_max__size: 512M
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data

  api:
    build: .
    depends_on:
      - neo4j
    environment:
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USERNAME: neo4j
      NEO4J_PASSWORD: pleaseChangeMe
      NEO4J_DATABASE: neo4j
      APP_HOST: 0.0.0.0
      APP_PORT: 8000
      WORKDIR: /tmp/supergraph_work
    ports:
      - "8000:8000"

volumes:
  neo4j_data:
